name: Greetings

on : [ pull_request , issues ]
Cvičení
práce :
  greeting:
    run-on : 
    kroky  :android 
    - používá   : akce / první interakce @ v19.0
      s:
        repo-token  : $ {{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users'' first issue'
        pr-message : 'Zpráva, která se zobrazí na uživatelích' 'první pr'
Cvičení
Cvičení
